import type { NextPage } from 'next'
import React  from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Principal: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Solicitar cita a un taller
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Agendar una cita en un Taller
        </h1>
        <div className={styles.grid}>
          <a
            href="./agendar.tsx"
            className={styles.card}>
            <h2>Agendar &rarr;</h2>
            <p>
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Principal
