version: '3'

services:
  api:
    build: .
    depends_on:
      - mongo
      # dependecias usadas para nuestro docker
    environment:
      - PORT=3000
      # Definir el puerto donde se ejecuta el programa
      - MONGODB_CNN=mongodb://mongo:27017/test
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    # Crear imagen de mongo