"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Vehiculo = exports.Taller = exports.Usuario = exports.Citas = void 0;
const ModelsCitas_1 = require("./ModelsCitas");
Object.defineProperty(exports, "Citas", { enumerable: true, get: function () { return ModelsCitas_1.Citas; } });
const ModelsCliente_1 = require("./ModelsCliente");
Object.defineProperty(exports, "Usuario", { enumerable: true, get: function () { return ModelsCliente_1.Usuario; } });
const ModelsTaller_1 = require("./ModelsTaller");
Object.defineProperty(exports, "Taller", { enumerable: true, get: function () { return ModelsTaller_1.Taller; } });
const ModelsVehiculo_1 = require("./ModelsVehiculo");
Object.defineProperty(exports, "Vehiculo", { enumerable: true, get: function () { return ModelsVehiculo_1.Vehiculo; } });
