"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const controllers_1 = require("../controllers");
const router = (0, express_1.Router)();
exports.router = router;
router.get('/talleres');
router.get('/vCita');
router.put('/dcita/:id', controllers_1.elminaCita);
router.post('/ncliente');
router.post('/nvehiculo');
router.post('/ncita', controllers_1.crearCita);
