"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const controllers_1 = require("../controllers");
const router = (0, express_1.Router)();
exports.router = router;
router.get('/talleres', controllers_1.verTalleres);
router.get('/vCita/:id', controllers_1.verCitasCliente);
router.get('/existe', controllers_1.existClient);
router.put('/dcita/:id', controllers_1.elminaCita);
router.post('/ncliente', controllers_1.crearCliente);
router.post('/ncita', controllers_1.crearCita);
