"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.verTalleres = exports.crearCliente = exports.editarTaller = exports.elminaCita = exports.crearTaller = exports.crearCita = void 0;
const CitaControllers_1 = require("./CitaControllers");
Object.defineProperty(exports, "crearCita", { enumerable: true, get: function () { return CitaControllers_1.crearCita; } });
Object.defineProperty(exports, "elminaCita", { enumerable: true, get: function () { return CitaControllers_1.elminaCita; } });
const CrearCliente_1 = require("./CrearCliente");
Object.defineProperty(exports, "crearCliente", { enumerable: true, get: function () { return CrearCliente_1.crearCliente; } });
const TallerControllers_1 = require("./TallerControllers");
Object.defineProperty(exports, "crearTaller", { enumerable: true, get: function () { return TallerControllers_1.crearTaller; } });
Object.defineProperty(exports, "editarTaller", { enumerable: true, get: function () { return TallerControllers_1.editarTaller; } });
Object.defineProperty(exports, "verTalleres", { enumerable: true, get: function () { return TallerControllers_1.verTalleres; } });
