//Esta hecho en SSR
import Head from 'next/head'
import style from '../styles/Home.module.css'
import {ChangeEvent, FormEvent, useEffect, useState} from 'react'
import Link from 'next/link'
import { ExistCliente } from '../services/Services'
import { NextApiHandler } from 'next'
import { respuesta } from '../interfaces/InterfacesT'



export default function Personajes(){
  const useFormVehiculo = () => {
    const id = JSON.parse( localStorage.getItem( 'user' ) || '{}' )
    const [vehiculo, setVehiculo] = useState( {
        placaVehiculo    : '',
        marcaVehiculo    : '',
        modeloVehiculo   : '',
        tipoVehiculo     : '',
        matriculaVehiculo: '',
        seguroVehiculo   : '',
        valorAlquilerDia : 0,
        usuario_ID       : '',
    } )

    const handleChange = ( e: ChangeEvent<HTMLInputElement> ) => {
        setVehiculo( {
            ...vehiculo,
            [e.target.name]: e.target.value,
        } )
    }

    return {
        vehiculo,
        handleChange,
        id,
    }
}
    
  return (
    <div >
      <Head>
        <title>Identificación</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"></link>
      </Head>

      <main className={style.main}>
        <h1 className="text-center">
          Identifiquese con su cédula
        </h1>
        <div className="container">
            <form onSubmit={getServerSideProps} method="post">
            
              <div className="form-group">
                  <label htmlFor="nombre">Cedúla</label>
                  <input type="text" className="form-control" id="ci" name="ci"  />
              </div>
              
              <button type="submit" className="btn btn-primary">Comprobar</button>
        
            </form>
        </div>
      <Link href='/' >
          <a   className="btn btn-primary">Atrás</a>
      </Link> 
      </main>
    </div>
      )
}

export async function getServerSideProps() {
  const data:String=cedula;
  const res = await ExistCliente('clientf/existe/', data)
  const dato = await res

  return {
    props: {characters: data.results}, // will be passed to the page component as props
  }
}