//Esta hecho en SSR
import Head from 'next/head'
import style from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import Link from 'next/link'
import { ExistCliente } from '../services/Services'
import { Cliente } from '../interfaces/InterfacesT'
const cedula = {
    ci: String
}
interface respuesta  {
    existe: Boolean
    ciente?: Object
    ci?:String
}
export default function Personajes(){

    async function getServerSideProps(req: Request)  {
        const res = ExistCliente<respuesta>('clientf/existe/',{
            ci: req.body.ci
        });
        const data = await res.json()
    
        return {
          props: {characters: data.results}, // will be passed to the page component as props
        }
    }

  return (
    <div >
      <Head>
        <title>Identificación</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>
        <h1 className={style.title}>
          Identifiquese con su cédula
        </h1>
        <div className={style.grid}>
            <form action="/productoForm/producto/operar" method="post">
            
            <div className="form-group">
                <label htmlFor="nombre">Cedúla</label>
                <input type="text" className="form-control" id="ci" name="ci"  />
            </div>
            
            <button type="submit" className="btn btn-primary">Comprobar</button>
        
            </form>
        </div>
      <Link href='/' >
          <a   className={style.back}>Atrás</a>
      </Link> 
      </main>
    </div>
      )
}

