import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
<<<<<<< HEAD
        <title>FRONT END</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
=======
>>>>>>> b291fb4240271862ce4e1a15c78335a268444df8
      </Head>
      <main className={styles.main}>
<<<<<<< HEAD
        <h1 className={styles.title}>
          Bienvenido a Sistema de Citas en Taller
        </h1>

        <p className={styles.description}>
          
        </p>

        <div className={styles.grid}>
          <section className={styles.title}>
            Rol: <Link href='/indentifi'>
            <a>CLIENTE</a>
            </Link> 
          </section>
        </div>
=======
>>>>>>> b291fb4240271862ce4e1a15c78335a268444df8
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
