//Esta hecho en SSR
import Head from 'next/head'
import style from '../styles/Home.module.css'
import {ChangeEvent, FormEvent, useState} from 'react'
import Link from 'next/link'
import { ExistCliente } from '../services/Services'
import Swal from 'sweetalert2'
import { respuesta } from '../interfaces/InterfacesT'
import { AxiosError } from 'axios'
import { useRouter } from 'next/router'





export default function Identifi(){
    const router = useRouter()
    const [recurso, setrecurso]= useState<respuesta>({
      ci : '',
      existe: true || false ,
      cliente: {}
    })
    const handleChange = ( e: ChangeEvent<HTMLInputElement> ) => {
        setrecurso( {
            ...recurso,
            [e.target.name]: e.target.value,
        } )
    }
    const handleSubmit = ( e: FormEvent<HTMLFormElement> ) => {
      e.preventDefault()
      const { ci } = recurso
       ExistCliente( ci )
            .then( ( res ) => {
                console.log( res )
                if (res.existe===false) {
                  setTimeout(async ()=>{
                    Swal.fire('Usted no está reistrado!') 
                  }
                  ,3000);
                  
                  router.push( '/RegistroCliente/');
                } else {
                  setTimeout(async ()=>{
                    Swal.fire('Usted está registrado!') 
                  }
                  ,3000);
                  router.push('/TresComponentes');
                }
                
                
            } )
            .catch( ( error: AxiosError) => {
                console.log( error)
            } )
  }

    
  return (
    <div >
      <Head>
        <title>Identificación</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"></link>
      </Head>

      <main className={style.main}>
        <h1 className="text-center">
          Identifiquese con su cédula
        </h1>
        <div className="container">
            <form onSubmit={handleSubmit} method="post">
            
              <div className="form-group">
                  <label htmlFor="nombre">Cedúla</label>
                  <input onChange={handleChange} className="form-control" type="text"  id="ci" name="ci"  />
              </div>
              
              <button type="submit" className="btn btn-primary">Comprobar</button>
        
            </form>
        </div>
      <Link href='/' >
          <a   className="btn btn-primary">Atrás</a>
      </Link> 
      </main>
    </div>
      )
}

